### ISSUE TITLE
[BUG] scrollbar-container class with height: 100 overwriting custom height

### ISSUE THREAD

**Issue by ggwzrd** [goldenyz/react-perfect-scrollbar#98]
With the latest update the property `height: 100%` has been added to the `scrollbar-container` class.

```css
.scrollbar-container {
    position: relative;
    height: 100%;
}
```

This property is overwriting the custom height set by my own class in css, forcing me to add an extra layer of specification in my css. 

```css
.my-class.scrollbar-container {
    height: 80px;
}
```

The expected behaviour is that I can set my own height without needing the extra `.scrollbar-container` specification.

```css
.my-class {
    height: 80px;
}
```

If this issue is approved then I can create a PR to fix this.
